Resources:
  AnalyticsBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  FirehoseStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: !GetAtt AnalyticsBucket.Arn
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 1
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref FirehoseLogGroup
          LogStreamName: !Ref FirehoseLogStream
        CompressionFormat: GZIP
        RoleARN: !GetAtt FirehoseDeliveryIamRole.Arn
        Prefix: analytics/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/hour=!{timestamp:HH}/
        ErrorOutputPrefix: analytics_errors/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/hour=!{timestamp:HH}/!{firehose:error-output-type}
        ProcessingConfiguration:
          Enabled: true
          Processors:
            - Type: AppendDelimiterToRecord
              Parameters:
                - ParameterName: Delimiter
                  ParameterValue: \n
  
  FirehoseLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 14

  FirehoseLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName:
        Ref: FirehoseLogGroup

  FirehoseDeliveryIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: root # TODO: might need to replace
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                Resource:
                  - !GetAtt AnalyticsBucket.Arn
                  - !Sub ${AnalyticsBucket.Arn}/*
              - Effect: Allow
                Action: logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${FirehoseLogGroup}:log-stream:*

  # Glue config

  AnalyticsGlueDb:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput: 
        Name: ${self:custom.analytics.glueDb}
        Description: "Analytics database for ${self:service} (${self:provider.stage})"
      DatabaseName: ${self:custom.analytics.glueDb}

  AnalyticsCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:service}-${self:provider.stage}-GlueCrawler
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3AccessForCrawler
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub ${AnalyticsBucket.Arn}
                  - !Sub ${AnalyticsBucket.Arn}/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws-glue/crawlers:*

  AnalyticsGlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: ${self:custom.analytics.glueCrawler}
      DatabaseName: ${self:custom.analytics.glueDb}
      Role: !GetAtt AnalyticsCrawlerRole.Arn
      # Schedule:                                // Note: commented out to signify, ON_DEMAND
      #   ScheduleExpression: cron(15 12 * * ? * // eg. run daily at 15 past noon UTC [12:15Z]
      SchemaChangePolicy: 
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "DELETE_FROM_DATABASE"
      Targets:
        S3Targets:
          # Note: */analytics sub-folder, within bucket
          - Path: !Sub s3://${AnalyticsBucket}/analytics

  # Athena config

  AnalyticsResults:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # NOTE: very useful for prod deployments, encryption at rest
      # BucketEncryption:
      #     ServerSideEncryptionConfiguration:
      #       - ServerSideEncryptionByDefault:
      #           SSEAlgorithm: AES256

  AthenaResultsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AnalyticsResults
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: athena.amazonaws.com
            Action:
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:ListMultipartUploadParts
              - s3:AbortMultipartUpload
              - s3:PutObject
            Resource:
              - !Sub ${AnalyticsResults.Arn}
              - !Sub ${AnalyticsResults.Arn}/*
            Condition:
              StringEquals:
                "aws:SourceAccount": !Ref AWS::AccountId
              StringLike:
                "aws:SourceArn": !Sub arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/*

  AnalyticsWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: ${self:custom.analytics.athena}
      Description: "${self:service}/analytics queries"
      RecursiveDeleteOption: true
      State: ENABLED
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: true
        ResultConfiguration:
          OutputLocation: !Sub s3://${AnalyticsResults}/results/