Resources:  
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      Tags:
        - Key: Environment
          Value: ${self:custom.stage}
        - Key: Name
          Value: users-table
        - Key: CanIDelete
          Value: 'No'
        - Key: Author
          Value: 'Alan Ionita'
        - Key: CreatedOn
          Value: 2025-03-04
  TweetsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: author
          AttributeType: S
        - AttributeName: retweetOf
          AttributeType: S
        - AttributeName: inReplyToTweetId
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: byCreator
          KeySchema:
            - AttributeName: author
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: retweets
          KeySchema:
            - AttributeName: author
              KeyType: HASH
            - AttributeName: retweetOf
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: replies
          KeySchema:
            - AttributeName: author
              KeyType: HASH
            - AttributeName: inReplyToTweetId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: ${self:custom.stage}
        - Key: Name
          Value: tweets-table
        - Key: CanIDelete
          Value: 'No'
        - Key: Author
          Value: 'Alan Ionita'
        - Key: CreatedOn
          Value: 2025-03-17
  TimelinesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: tweetId
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: tweetId
            AttributeType: S
        Tags:
          - Key: Environment
            Value: ${self:custom.stage}
          - Key: Name
            Value: timelines-table
          - Key: CanIDelete
            Value: 'No'
          - Key: Author
            Value: 'Alan Ionita'
          - Key: CreatedOn
            Value: 2025-03-17
  TweetLikesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: tweetId
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: tweetId
          AttributeType: S
      Tags:
        - Key: Environment
          Value: ${self:custom.stage}
        - Key: Name
          Value: tweet-likes-table
        - Key: CanIDelete
          Value: 'No'
        - Key: Author
          Value: 'Alan Ionita'
        - Key: CreatedOn
          Value: 2025-03-20
  RetweetsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: tweetId
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: tweetId
          AttributeType: S
      Tags:
        - Key: Environment
          Value: ${self:custom.stage}
        - Key: Name
          Value: retweets-table
        - Key: CanIDelete
          Value: 'No'
        - Key: Author
          Value: 'Alan Ionita'
        - Key: CreatedOn
          Value: 2025-03-21
  RelationshipsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: otherUserId
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: byOtherUser
          KeySchema:
            - AttributeName: otherUserId
              KeyType: HASH
            - AttributeName: sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: ${self:custom.stage}
        - Key: Name
          Value: relationships-table
        - Key: CanIDelete
          Value: 'No'
        - Key: Author
          Value: 'Alan Ionita'
        - Key: CreatedOn
          Value: 2025-05-08